### ISSUE TITLE
Add optional argument to corrmorant specifying if font size of correlations should be dependent on magnitude.

### ISSUE THREAD

**Issue by pepijnvink** [r-link/corrmorant#27]
When font size of the correlations are dependent on the magnitude of these correlations, this may decrease legibility when some correlations are relatively small. It would be great to have an optional argument specifying if the font size should be correlation dependent (defaulting to TRUE). 

This could be done by specifying the corr_size argument in the utri_corrtext() function for the layers dependent on the optional argument.

**Comment by r-link** [comment]
Hi there,

I am not sure I understand what you mean. By setting `corr_size = FALSE`, you can do just that - in this case, the font size is not correlation dependent. 

If the legibility of small correlations is a problem, you could also use  `scale_size(range = c(<lower size limit>, <upper size limit>))` to manually override the size scale. The defaults here are `c(1, 6)` but sometimes that can be hard to read.

Does this do what you need?
